### PR TITLE
Edit: Made changes to follow the custom lints patter and updates the …

### LINKED ISSUE #2111: Upgrade package lint from 2.1.2 to 2.2.0
For security purposes, we need to bump package [lint](https://github.com/passsy/dart-lint) from 2.1.2 to 2.2.0.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa/pull/2102

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa/actions/runs/6908289518/job/18797250509?pr=2102

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

### PR DESCRIPTION
**Pull request by vaidic-dodwani**
This change included the bumping of lint from 2.1.2 to 2.2.0.

Issue Number:

Fixed #2111 

Did you add tests for your changes?

No tests are required for this change as it only includes a package update.

If relevant, did you update the documentation?

Updation the documentation isnt required for this.

Summary

It upgrades the lint to 2.2.0 for enhanceability.

Does this PR introduce a breaking change?

No, this does not introduce any major changes to the codebase.

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?

Yes, i have followed the guidelines.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the conflicting files.

@aashimawadhwa will be handling all issue queries and seeking reviewers for PRs. When necessary, this contributor will contact other contributors who will be able to assist. Please ask them for guidance on your future questions.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please add tests for the missing lines in the edited files. `add_post_view_model.dart` and `edit_profile_view_model.dart`

File: lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart [hunk 1]
```diff
@@ -63,26 +61,6 @@ class EditProfilePageViewModel extends BaseModel {
...
-      print(base64String);
-      imageFile = base64String as File?;
-      return base64String;
-    } catch (error) {
-      return '';
-    }
-  }
-
   /// This function remove the selected image.
   ///
```
Comment (noman2002) [inline lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart:65]: Why we need to remove this ?

Comment (vaidic-dodwani) [reply lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart:65]: This function is not being used by the views, in edit_profile, whereas it  is being used in the add_profile segment. And so I have removed it from here and added tests for this function used in add_profile tests

**Comment by vaidic-dodwani** [comment]
@noman2002 i think everything everything is up to the mark, or should i add some changes?

**Comment by Dante291** [comment]
@noman2002 @palisadoes I have upgraded Lint package in [this](https://github.com/PalisadoesFoundation/talawa/pull/2140) PR which just got merged.

**Comment by noman2002** [comment]
@vaidic-dodwani  Please fix the conflicting files. And take a latest pull.

**Comment by vaidic-dodwani** [comment]
@noman2002 i have solved the conflicts

**Comment by palisadoes** [comment]
@literalEval What are your thoughts on this?

File: lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart [hunk 2]
```diff
@@ -63,25 +61,6 @@ class EditProfilePageViewModel extends BaseModel {
...
-      final List<int> bytes = await file.readAsBytes();
-      final String base64String = base64Encode(bytes);
-      print(base64String);
-      imageFile = base64String as File?;
-      return base64String;
-    } catch (error) {
-      return '';
-    }
-  }
-
```
Comment (noman2002) [inline lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart:84]: Why we need to remove this function ?

**Comment by literalEval** [comment]
@vaidic-dodwani are you able to run the custom linter in your IDE ? ie - Does custom lint warnings appear on no-doc fields ? If yes, do they still appear after this package update ?

File: lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart (hunk 2 above)
Comment (vaidic-dodwani) [reply lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart:84]: the above function is not being used in edit_profile section, but is being used in add_profile section, and so i have removed it from here and added corresponding tests in add_profile section

**Comment by vaidic-dodwani** [comment]
@literalEval  yes, after the upgradation i saw warning on two files which i then resolved, earlier the warnings were not there.

**Comment by literalEval** [comment]
Can you please get those errors again and share a screenshot of the warning ?

**Review by noman2002 — APPROVED** [review]
Looks good to me.

File: lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart (hunk 2 above)
Comment (literalEval) [reply lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart:84]: @vaidic-dodwani where is this code moved ? No file change shows the addition. Moreover, converting files to base64 seems to be a common feature that can be used by many files, so it'll be better to have this func in a separate service (say ImageService), instead of moving to specific files.

Comment (literalEval) [reply lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart:84]: @vaidic-dodwani where is this code moved ? No file change shows the addition. Moreover, converting files to base64 seems to be a common feature that can be used by many files, so it'll be better to have this func in a separate service (say ImageService), instead of moving to specific files.

**Review by literalEval — CHANGES_REQUESTED** [review]

File: lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart (hunk 2 above)
Comment (vaidic-dodwani) [reply lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart:84]: @literalEval The code segment isn't moved, it was already present where it is required, it didn't have tests which are now added.
Regarding the separate service, I think the function isn't used anywhere else so it doesn't make a great difference, in future if it is required I think then we should make a ImageService.

**Comment by vaidic-dodwani** [comment]
@literalEval @noman2002 hey, may i know the issue for this PR?

**Comment by noman2002** [comment]
@vaidic-dodwani Please have a look at the review provided by @literalEval

**Comment by noman2002** [comment]
Please take a latest pull on this branch. I think we can merge this.

**Comment by vaidic-dodwani** [comment]
@noman2002 i think everythings upto the mark now.

**Comment by noman2002** [comment]
@literalEval Please review this.

**Comment by vaidic-dodwani** [comment]
@literalEval @noman2002 hey, can i get approval for these?

**Comment by literalEval** [comment]
@vaidic-dodwani change the PR title. LGTM otherwise.

**Review by palisadoes — APPROVED** [review]
