### PR TITLE
fixed fetch post by org

### LINKED ISSUE #2404: Change of query post by organization
Describe the bug
Post by organisation query need to be changed according to this PR #1722

Additional details
As PR [#1722 ](https://github.com/PalisadoesFoundation/talawa-api/pull/1722)changed the implementation of the PostByOrganization query,this need to be changed in admin and mobile repo as soon as possible

Potential internship candidates
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AVtheking**
**What kind of change does this PR introduce?**
Changed postByOrganization query according to new paginatied query in the api.

**Issue Number:**

Fixes #2404 

**Did you add tests for your changes?**
Yes

**Video**

https://github.com/PalisadoesFoundation/talawa/assets/132201033/27968561-a35d-44a3-9a24-44aa164deb58

### CODE REVIEW

**Comment by AVtheking** [comment]
@Cioppolo14 I have fixed failing codecov tests.

**Comment by AVtheking** [comment]
I have fixed failing test ,please assign reviewers .

File: lib/services/post_service.dart [hunk 1]
```diff
@@ -75,18 +81,21 @@ class PostService {
   Future<void> getPosts() async {
     // variables
     final String currentOrgID = _currentOrg.id!;
-    final String query = PostQueries().getPostsById(currentOrgID);
+    final String query =
+        PostQueries().getPostsById(currentOrgID, after, before, first, last);
     final result = await _dbFunctions.gqlAuthQuery(query);
-
+    // print(result.data);
```
Comment (Ayush0Chaudhary) [inline lib/services/post_service.dart:87]: rmv // statements

File: lib/services/post_service.dart [hunk 2]
```diff
@@ -1,4 +1,4 @@
-// ignore_for_file: talawa_good_doc_comments, talawa_api_doc
+// ignore_for_file: talawa_good_doc_comments, talawa_api_doc, avoid_dynamic_calls
```
Comment (Ayush0Chaudhary) [inline lib/services/post_service.dart:1]: Don't Avoid method calls or property accesses on a "dynamic" target

**Review by Ayush0Chaudhary — CHANGES_REQUESTED** [review]

File: lib/services/post_service.dart (hunk 2 above)
Comment (AVtheking) [reply lib/services/post_service.dart:1]: Sir on removing this it is giving avoid dynamic call suggestion

Comment (Ayush0Chaudhary) [reply lib/services/post_service.dart:1]: So avoid it instead of adding an ignore statement. 

Adding ignore statements for solvable issues is not good practice

Comment (AVtheking) [reply lib/services/post_service.dart]: Done fixing it.

**Comment by AVtheking** [comment]
@Ayush0Chaudhary I have made changes requested by you please review.

**Comment by noman2002** [comment]
@AVtheking Having a button to move to next page is not a good approach in a feed like structure. Please do it without the buttons.

**Comment by AVtheking** [comment]
> @AVtheking Having a button to move to next page is not a good approach in a feed like structure. Please do it without the buttons.

Ok will look into it,are you talking about scrolling approach?

**Comment by noman2002** [comment]
please share a updated video.

**Comment by AVtheking** [comment]
@noman2002 I have shared the updated video
But the previous test are failing due to this it is giving me this error 
image
it was not showing this error before this approach .

**Comment by AVtheking** [comment]
@noman2002 please look into it

File: lib/services/post_service.dart [hunk 3]
```diff
@@ -1,4 +1,4 @@
-// ignore_for_file: talawa_good_doc_comments, talawa_api_doc
+// ignore_for_file: talawa_good_doc_comments, talawa_api_doc,
```
Comment (noman2002) [inline lib/services/post_service.dart:1]: Remove this and add comments.

File: lib/views/after_auth_screens/feed/organization_feed.dart [hunk 4]
```diff
@@ -71,58 +89,94 @@ class OrganizationFeed extends StatelessWidget {
...
-                                  ),
-                                  child: Text(
-                                    AppLocalizations.of(context)!
-                                        .strictTranslate(
-                                      'There are no posts in this organization',
+                  child: NotificationListener<ScrollNotification>(
+                    onNotification: (notification) {
+                      final maxScroll =
+                          _scrollController.position.maxScrollExtent;
+                      final currentScroll = _scrollController.position.pixels;
```
Comment (noman2002) [inline lib/views/after_auth_screens/feed/organization_feed.dart:96]: Add test for these lines.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Make the suggested changes and revert the changes in pubspec.lock as it is not required.

**Comment by AVtheking** [comment]
> @noman2002 I have shared the updated v image it was not showing this error before this approach .

@noman2002  When I am writing test to mock scroll behaviour it is giving me this error

**Comment by Azad99-9** [comment]
@AVtheking I too have faced the same issue multiple times. From that what I got to know is, the error is not related to http request but it is related to the test you are currently working on. Try to fix your test I mean the scroll behavior one, automatically the http error will disappear. I think it's some kind of glitch or something.

I think this may help.

**Comment by AVtheking** [comment]
> @AVtheking I too have faced the same issue multiple times. From that what I got to know is, the error is not related to http request but it is related to the test you are currently working on. Try to fix your test I mean the scroll behavior one, automatically the http error will disappear. I think it's some kind of glitch or something.
> 
> I think this may help.

But what to fix in the test it is giving me error at the moment I implemented drag, Refresh Indicator which was before passing failed after I used notification listener giving me this same warning

**Comment by AVtheking** [comment]
@noman2002 this http error is still showing ,can we merge this and open issue write test for this ? As this funcitonality needs to be resolved

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by noman2002** [comment]
> @noman2002 this http error is still showing ,can we merge this and open issue write test for this ? As this funcitonality needs to be resolved

Please work with @Azad99-9 and get this fixed in this PR.

**Comment by Azad99-9** [comment]
@AVtheking please check the app is failing to build.

**Comment by AVtheking** [comment]
@Azad99-9 i have tried building it in my local it is working fine,what could be the reason of this fail?

**Comment by Azad99-9** [comment]
Have you downgraded any packages ?

**Comment by AVtheking** [comment]
No just merged with latest upstream

**Comment by Azad99-9** [comment]
If you didn't downgrade any packages then It might be a transient bug. Please please do a minor commit and try to rebuild the app.

**Comment by Azad99-9** [comment]
@AVtheking I have solved the HTTP bug for this issue. please do the below-suggested code changes. You will be good to go.

File: test/widget_tests/after_auth_screens/feed/organization_feed_test.dart [hunk 5]
```diff
@@ -161,31 +161,6 @@ void main() {
       expect(finder, findsOneWidget);
     });
 
-    testWidgets('check if refresh Indicator works fine', (tester) async {
-      when(mockViewModel.currentOrgName).thenReturn('testOrg');
-      when(mockViewModel.isFetchingPosts).thenReturn(false);
-      when(mockViewModel.isBusy).thenReturn(false);
-      when(mockViewModel.initialise()).thenReturn(null);
-      when(mockViewModel.posts).thenReturn([post]);
```
Comment (Azad99-9) [inline test/widget_tests/after_auth_screens/feed/organization_feed_test.dart:169]: replace [post] with [post, post, post, post, post, post]

File: lib/views/after_auth_screens/feed/organization_feed.dart [hunk 6]
```diff
@@ -71,58 +89,94 @@ class OrganizationFeed extends StatelessWidget {
...
+                          firstUpScroll++;
+                        }
+                      }
+                      // Reset counters if scrolling occurs anywhere other than at the edge
+                      if (!notification.metrics.atEdge) {
+                        firstDownScroll = 0;
+                        firstUpScroll = 0;
+                      }
+
+                      return true;
```
Comment (Azad99-9) [inline lib/views/after_auth_screens/feed/organization_feed.dart:124]: return `false` here.

**Comment by Azad99-9** [comment]
The reason for the bug was:
1. The `RefreshIndicator` requires scrollNotifications to work properly.
2. When we return `true` from `onNotification` Call back we are essentially making the scroll notifications to be consumed by the `NotificationListener` itself and not letting it to propagate up the widget tree till the `RefreshIndicator`. So the RefreshIndicator was never being refreshed in the first place.
3. By returning `false` we are letting the scroll notifications to propagate till the RefreshIndicator thus allowing it to refresh smoothly.

As mentioned after doing this the HTTP bug has implicitly `vanished` as it is just a warning.

I have only solved the HTTP bug and made the test run successfully. You please cover all the remaining lines by writing tests to all possible situations to cover the if blocks in `onNotification` call back.

Feel free to reach out to me if you need any more futher assistance. Thank you.

**Comment by AVtheking** [comment]
@Azad99-9 Thanks ,I would try this.

**Comment by AVtheking** [comment]
please review this PR.

**Review by palisadoes — APPROVED** [review]
