### PR TITLE
Fixes #2192 #1602 , Improving Filters UI

### LINKED ISSUE #2192: The Event filtering button is not intuitive to use
**Describe the bug**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.

Event filtering button is not intuitive. It says `Add Date` versus  something easier to understand. Changing the wording may not be enough. An easier to use and understand methodology should be considered.

**To Reproduce**

1. Open the mobile app
2. Click on `Events`
3. You'll see the `Add Date` filter in the top right hand corner

**Expected behavior**

1. A more intuitive interface is required
2. Filtering by date must be maintained

**Actual behavior**
See video:

- https://youtu.be/86AzK_Y_GCQ?t=276

**Screenshots**
- N/A

**Additional details**
- You must get the test **_code coverage up to 100%_** for any edited files. No functionality must be removed to achieve this goal.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AyushRaghuvanshi**
**What kind of change does this PR introduce?**

Feature : Improved the Filter UX and Filter by Date button.

**Issue Number:**

Fixes #2192 #1602
**Did you add tests for your changes?**

Its Just refactoring the UI. no tests required

**Snapshots/Videos:**
image

image

image

image

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by AyushRaghuvanshi** [comment]
@noman2002 @palisadoes What do you suggest for the count of lines. I think It requires this much code.

**Comment by noman2002** [comment]
> @noman2002 @palisadoes What do you suggest for the count of lines. I think It requires this much code.

Make components and reduce the number of lines in that particular file.

**Comment by AyushRaghuvanshi** [comment]
@noman2002 Can you review please?

File: lib/views/after_auth_screens/events/event_filter_bottomsheet.dart [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+                Row(
+                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
+                  children: [
+                    Text(
+                      AppLocalizations.of(context)!.strictTranslate("Filters"),
+                      style: Theme.of(context).textTheme.headlineSmall,
+                    ),
+                    IconButton(
+                      onPressed: () {
+                        Navigator.pop(context);
```
Comment (noman2002) [inline lib/views/after_auth_screens/events/event_filter_bottomsheet.dart:47]: Please write the test.

File: lib/views/after_auth_screens/events/event_filter_bottomsheet.dart [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+                    ),
+                  ],
+                ),
+                ...List.generate(filters.length, (index) {
+                  return Padding(
+                    padding: const EdgeInsets.symmetric(vertical: 8.0),
+                    child: GestureDetector(
+                      onTap: () {
+                        model.choseValueFromDropdown(
+                          filters.keys.toList()[index],
```
Comment (noman2002) [inline lib/views/after_auth_screens/events/event_filter_bottomsheet.dart:59]: Please write the test.

File: lib/views/after_auth_screens/events/event_filter_bottomsheet.dart [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+                        );
+                        setState(() {});
```
Comment (noman2002) [inline lib/views/after_auth_screens/events/event_filter_bottomsheet.dart:61]: Please write the test.

**Review by noman2002 — CHANGES_REQUESTED** [review]

**Comment by AyushRaghuvanshi** [comment]
I have my exams going on. I will write these tests as soon as I get time. Sorry for the inconvenience

File: lib/services/navigation_service.dart [hunk 4]
```diff
@@ -118,6 +126,17 @@ class NavigationService {
     );
   }
 
+  /// This is used for the quick error of `duration: 2 seconds`.
+  ///
+  /// more_info_if_required
```
Comment (literalEval) [inline lib/services/navigation_service.dart:131]: Remove this line. Edit the doc template accordingly.

File: test/service_tests/navigation_service_test.dart [hunk 5]
```diff
@@ -232,6 +263,14 @@ class TalawaErrorWidget extends StatelessWidget {
   }
 }
 
+///Tests Navigation Service.
```
Comment (literalEval) [inline test/service_tests/navigation_service_test.dart:266]: Fix spacing and new line.

File: test/view_model_tests/after_auth_view_model_tests/add_post_view_model_test.dart [hunk 6]
```diff
@@ -10,10 +10,27 @@ import 'package:talawa/view_model/after_auth_view_models/add_post_view_models/ad
...
 
+/// Contains All test for Add Post View Model .
+///
+/// more_info_if_required
+///
+/// **params**:
+///   None
+///
+/// **returns**:
+///   None
```
Comment (literalEval) [inline test/view_model_tests/after_auth_view_model_tests/add_post_view_model_test.dart:33]: You don't need to write documentation for main function. Please read the doc guideline once.

**Review by literalEval — CHANGES_REQUESTED** [review]
Add proper spacing/new-lines and improve documentation.

File: pubspec.lock [hunk 7]
```diff
@@ -1834,5 +1834,5 @@ packages:
     source: hosted
     version: "3.1.2"
 sdks:
-  dart: ">=3.2.0-194.0.dev <3.13.0"
-  flutter: ">=3.13.0"
+  dart: ">=3.2.0 <3.13.0"
+  flutter: ">=3.16.0"
```
Comment (literalEval) [inline pubspec.lock:1838]: Why is this bump in this PR ?

**Comment by AyushRaghuvanshi** [comment]
@literalEval made the changes you requested. Please Review.

File: test/service_tests/navigation_service_test.dart [hunk 8]
```diff
@@ -133,9 +149,16 @@ class _FirstScrenState extends State<FirstTestScreen> {
...
+/// Test Screens.
 class SecondTestScreen extends StatefulWidget {
   const SecondTestScreen({super.key, this.arguments, this.onclick});
+
+  /// Arguements.
   final String? arguments;
+
+  /// a_line_ending_with_end_punctuation.
+  ///
+  /// more_info_if_required
```
Comment (literalEval) [inline test/service_tests/navigation_service_test.dart:161]: Fix this doc.

**Review by literalEval — CHANGES_REQUESTED** [review]
1. You don't need to write documentation for test files. Read the doc guideline thoroughly.
2. Add proper spacing in documentation.

I'd suggest you to take smaller issues for now to get familiar with the codebase and documentation guidelines.

**Comment by AyushRaghuvanshi** [comment]
@literalEval can you point me to the doc where documentations guidelines are written? 

What I do is , I go with the custom lint and write documentation for each.

**Comment by literalEval** [comment]
@AyushRaghuvanshi [here](https://docs.talawa.io/docs/developers/talawa/talawa-lint). Have a look at the [official Dart documentation guidelines](https://dart.dev/effective-dart/documentation) too.

**Comment by AyushRaghuvanshi** [comment]
> @AyushRaghuvanshi [here](https://docs.talawa.io/docs/developers/talawa/talawa-lint). Have a look at the [official Dart documentation guidelines](https://dart.dev/effective-dart/documentation) too.

Understood. and have made changes according to that. @literalEval.

**Review by literalEval — CHANGES_REQUESTED** [review]
Use SizeConfig and not constant sizing.

**Review by literalEval — CHANGES_REQUESTED** [review]
Add trailing commas at the end of long lines and reformat.

**Review by literalEval — CHANGES_REQUESTED** [review]

File: lib/views/after_auth_screens/events/event_filter_bottomsheet.dart [hunk 9]
```diff
@@ -41,85 +44,100 @@ Widget dropDownList(ExploreEventsViewModel model, BuildContext context) {
...
+                          key: Key(
+                            '${filters.keys.toList()[index]}test',
+                          ),
+                          decoration: BoxDecoration(
+                            color: model.chosenValue ==
+                                    filters.keys.toList()[index]
+                                ? Theme.of(context).colorScheme.secondary
+                                : AppTheme.white,
+                            borderRadius: const BorderRadius.all(
+                              Radius.circular(8),
```
[the remark this answers is not in the document]
Comment (AyushRaghuvanshi) [reply lib/views/after_auth_screens/events/event_filter_bottomsheet.dart:92]: 8 here is radius.? do you want me to make this dynamic? I mean it would look weird to make it dependent upon the width or height. Also 8px radius would never cause any overflow error. 

I can do it. But I dont think there is any need. Also in whole project we are using constant radius only.

File: lib/views/after_auth_screens/events/event_filter_bottomsheet.dart [hunk 10]
```diff
@@ -41,85 +44,100 @@ Widget dropDownList(ExploreEventsViewModel model, BuildContext context) {
...
+                      child: GestureDetector(
+                        onTap: () {
+                          model.choseValueFromDropdown(
+                            filters.keys.toList()[index],
+                          );
+                          setState(() {});
+                        },
+                        child: Container(
+                          key: Key(
+                            '${filters.keys.toList()[index]}test',
```
[the remark this answers is not in the document]
Comment (AyushRaghuvanshi) [reply lib/views/after_auth_screens/events/event_filter_bottomsheet.dart:84]: Just to differentiate. Ill remove it.

**Comment by AyushRaghuvanshi** [comment]
@literalEval I have made the required changes. Can you review Please?

**Review by noman2002 — APPROVED** [review]
Looks fine.
@literalEval Please have a look.

**Comment by AyushRaghuvanshi** [comment]
@literalEval @palisadoes. I would like to work on More issues and this Pr is actually blocking both of my issues quota. Can you look into this?

**Review by palisadoes — APPROVED** [review]
