### PR TITLE
Solves issue #1024

### LINKED ISSUE #1024: The floating action button covers Event Card details.
**Describe the bug**
The Floating Action Button covers the public/private and the number of attendees details of the event card.

**To Reproduce**

1. Join an organization
2. Create an event.
3. Go to the 'Explore Events' page.
4. Check the bottom-most event card.

**Expected behavior**
The floating action button below the card and all details of the card are visible.

**Actual behavior**
The floating action button covers the last 2 rows of details.

**Screenshots**
https://drive.google.com/file/d/1hqjF0J_6uSo7LkJLioaKYRjNRbrfjWz-/view?usp=sharing

**Additional details**

I'm willing to work on this issue.

### PR DESCRIPTION
**Pull request by Simran1604**
**What kind of change does this PR introduce?**

 a bugfix

**Issue Number:**

Fixes #1024 
**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://drive.google.com/file/d/1xsfx9ouSvBBz15TCuhj6YfzJsIj3SPtv/view?usp=sharing

**If relevant, did you update the documentation?**
No

**Summary**
The Floating Action Button was covering the public/private and the number of attendees details of the event card. This bug is fixed by this PR.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

File: lib/views/after_auth_screens/events/explore_events.dart [hunk 1]
```diff
@@ -138,31 +138,34 @@ class ExploreEvents extends StatelessWidget {
...
-                                                "exploreEventViewModel": model
-                                              });
-                                        },
-                                        child: EventCard(
-                                          event: model.events[index],
-                                          isSearchItem: false,
-                                        ),
-                                      );
-                                    }),
+                                Padding(
```
Comment (sumitra19jha) [inline lib/views/after_auth_screens/events/explore_events.dart:141]: Please remove the padding from here. This will reduce user experience. We should give users as much screen area as possible. Padding should be added to the end card. As the user reaches the bottom of the screen (after scrolling) the card there should have padding space to let the user see the data which is hidden by the floating button.

File: lib/views/after_auth_screens/events/explore_events.dart [hunk 2]
```diff
@@ -138,31 +138,34 @@ class ExploreEvents extends StatelessWidget {
...
+                                  padding: const EdgeInsets.only(bottom: 60.0),
```
Comment (sumitra19jha) [inline lib/views/after_auth_screens/events/explore_events.dart:142]: Please do not use constants (like 60.0) in padding or margin value. Different devices have different screen heights, so the padding constant should be adjusted according to that. Use the Sizeconfig class already created to adjust the space. For example: Sizeconfig.screenheight * 0.01

**Comment by Simran1604** [comment]
@sumitra19jha I have updated the code. Pls, review.

**Comment by sumitra19jha** [comment]
> @sumitra19jha I have updated the code. Pls, review.

Can you please let me know what you have changed in file lib/widgets/event_card.dart

**Comment by Simran1604** [comment]
> > @sumitra19jha I have updated the code. Pls, review.
> 
> Can you please let me know what you have changed in file lib/widgets/event_card.dart

I haven't changed anything there.  Earlier had added some padding but removed it after consulting with you.

**Review by sumitra19jha — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@ Simran1604 Please resubmit this PR. You did not sync your repo correctly prior to submission and we are having issues with our GitHub actions.
