### PR TITLE
fix the event calender bug

### LINKED ISSUE #2328: EventCalendar screen failing to open.
**Describe the bug**
The `EventCalendar` screen is failing to open when the `ExploreEvents` screen is not empty.

**To Reproduce**

1. Navigate to Explore Events Page.
2. Create a new event.
3. Navigate back to Explore Events Page.
4. Open Event Calendar page by clicking on calendar icon.

**Expected behavior**
Screenshot_20240116-001427

**Actual behavior**
Screenshot_20240116-001659

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AVtheking**
**What kind of change does this PR introduce?**
fix the bug while opening event calender page 

**Issue Number:**

Fixes #2328 

**Did you add tests for your changes?**

NO

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@AVtheking Please fix the failing tests.

**Comment by AVtheking** [comment]
I have fixed the failing test cases

**Comment by Cioppolo14** [comment]
@Ayush0Chaudhary @CyberWake Can you review this PR?

**Comment by AVtheking** [comment]
please review this and suggest changes if any

File: lib/views/after_auth_screens/events/event_calendar.dart [hunk 1]
```diff
@@ -156,6 +154,21 @@ _AppointmentDataSource _getCalendarDataSource(List<Event> eventsList) {
...
+/// * `time`: define_the_param
+///
+/// **returns**:
+/// * `DateTime`: define_the_return
+DateTime _parseTime(String time) {
+  try {
+    return DateFormat('h:mm a', 'en_US').parse(time);
+  } catch (e) {
+    return DateFormat('Hms', 'en_US').parse(time);
+  }
```
Comment (Ayush0Chaudhary) [inline lib/views/after_auth_screens/events/event_calendar.dart:169]: Specify type of error using on clause, on return 'Hms' in case format exception, otherwise throw an error.
its not big issue, but for better code quality.

**Comment by AVtheking** [comment]
I have implemented the on clause to catch formatException error

File: lib/views/after_auth_screens/events/event_calendar.dart [hunk 2]
```diff
@@ -130,12 +130,10 @@ _AppointmentDataSource _getCalendarDataSource(List<Event> eventsList) {
...
     final startDate = DateFormat('yMd').parse(event.startDate!);
     print("${event.startTime!}##############################");
-    final startTime =
-        DateFormat('Hms', 'en_US').parse(event.startTime ?? '14:23:01');
+    final startTime = _parseTime(event.startTime ?? '14:23:01');
     // .parse(event.startTime!);
     final endDate = DateFormat('yMd').parse(event.endDate!);
-    final endTime =
-        DateFormat('Hms', 'en_US').parse(event.endTime ?? '14:23:01');
+    final endTime = _parseTime(event.endTime ?? '21:23:01');
```
Comment (noman2002) [inline lib/views/after_auth_screens/events/event_calendar.dart:136]: Changes looks fine but why we are using 14.23.01 as a default ?

File: lib/views/after_auth_screens/events/event_calendar.dart [hunk 3]
```diff
@@ -156,6 +154,25 @@ _AppointmentDataSource _getCalendarDataSource(List<Event> eventsList) {
...
+/// * `DateTime`: define_the_return
+DateTime _parseTime(String time) {
+  try {
+    return DateFormat('h:mm a', 'en_US').parse(time);
+  } on FormatException {
+    print('Caught FormatException: $time');
+    return DateFormat('Hms').parse(time);
+  } catch (e) {
+    print('Caught error: $e');
+    throw Exception('Invalid time format: $time');
```
Comment (noman2002) [inline lib/views/after_auth_screens/events/event_calendar.dart:172]: Write the tests for these lines.

**Review by noman2002 — CHANGES_REQUESTED** [review]

File: lib/views/after_auth_screens/events/event_calendar.dart (hunk 2 above)
Comment (AVtheking) [reply lib/views/after_auth_screens/events/event_calendar.dart:136]: It was already there as default value, therefore I just used that

File: lib/views/after_auth_screens/events/event_calendar.dart (hunk 3 above)
Comment (AVtheking) [reply lib/views/after_auth_screens/events/event_calendar.dart:172]: I have added test for these lines please review

**Review by noman2002 — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]
