### PR TITLE
Remove multiple instances of toast widgets and separate exceptions in toasts.

### LINKED ISSUE #594: [Bug] Toast text RenderFlex overflowed issue
- **Issue Description**
    At Create Organization page, Toast text RenderFlex overflowed issue

- **Issue Severity**
     Low

- **Observed Behaviour:**
     Toast text was overflowing by 303 pixels

- **Expected Behaviour:**
      Wrap text on overflow, like insert ellipsis or fade 

- **Steps to reproduce issue:**
      1. Open App
      2. Enter Url
      3. Try to Create organization

- **Snapshots/Videos:**

- **Does this issue need immediate attention?**
      Yes

- **Are you willing to work on this issue:**
     Yes

- **Other information:**
     Please assign this issue to me. @Sagar2366 @DeltaHarbinger sir

### LINKED ISSUE #716: Migration of all toasts to a common widget
- Parent issue : #715 
- **Issue Description:** <Add brief description about issue or feature you want to add.>
Migration of all the success and error toast to a common widget in` success_toast.dart`
The widget here needs some modifications to make it universal. Like it needs two required parameters `message` and` isSuccess `with an option parameter duration. After which this widget needs to be used at all the places in the project by just passing the `message`, `isSuccess`, and` duration` if needed. After successfully accomplishing the task the file `toast_tile.dart` can be deleted with the file `success_toast.dart` renamed to something more appropriate like` toast.dart `etc.
- **Issue Severity:** <High or Medium orLow>
Low
- **Environment Details:** <Add details about environment where this issue is found.>
Project Level
- **Observed Behaviour:** <Add details about your observation related to this issue.>
Toasts are coded multiple times, can be moved to single file
- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
Removal of unused widgets, unused files. Generation of reusable widgets
- **Does this issue need immediate attention?** <If yes. Please explain in detail>
No
- **Please ask mentors/maintainers to assign if you are willing to work on this issue.**

### PR DESCRIPTION
**Pull request by utkarshshendge**
**What kind of change does this PR introduce?**
This is a code refactor. And a minor UX improvement by showing users the type of exception.
This issue fixes #716 and 
Coincidentally fixes #594 .

**Did you add tests for your changes?**
No, not required

**Summary**
Instead of creating  separate widgets I directly used `FlutterToast.showTost()`. It gives us the same behavior, prevents text-overflow, and significantly reduces the number of lines in code.
Server exception and Client exception messages are separated:

https://user-images.githubusercontent.com/57677520/116474773-8e3f3580-a896-11eb-86b7-af2baa79cf54.mp4

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by utkarshshendge** [comment]
@palisadoes, @Sagar2366  could you please review and merge this PR  before merging another PR?
Because I have done changes in many files, and there may be merge conflicts again. Sometimes the conflicts are severe. This won't be the case with other PR's as not many files are changed.

File: lib/utils/exception_classifier.dart [hunk 1]
```diff
@@ -0,0 +1,9 @@
+String classifyException(String exceptionString) {
+  if (exceptionString.contains('ClientException')) {
```
Comment (dellyjm) [inline lib/utils/exception_classifier.dart:2]: Is ClientException related to client to connect to the API?

File: lib/views/pages/events/events.dart [hunk 2]
```diff
@@ -162,7 +161,8 @@ class _EventsState extends State<Events> {
     final String mutation = Queries().deleteEvent(eventId);
     final Map result = await apiFunctions.gqlquery(mutation);
     if (result["exception"] != null) {
-      _exceptionToast("Could not delete event! Please try again later");
+      CustomToast.exceptionToast(
```
Comment (dellyjm) [inline lib/views/pages/events/events.dart:164]: Does the type of exception matter here? If it's internet connectivity i.e. ClientException as you mentioned earlier then we should let them know that's the issue. Otherwise we show some other message if there is something they can do to resolve it. If nothing else, then generic error - maybe ask them to recreate it.

**Review by dellyjm — APPROVED** [review]

**Comment by dellyjm** [comment]
I approved the changes but please review my comments, I would like to have a response to them.

File: lib/utils/exception_classifier.dart (hunk 1 above)
Comment (utkarshshendge) [reply lib/utils/exception_classifier.dart:2]: Yes @dellyjm, the ClientException is thrown when a user tries to connect the API.

File: lib/views/pages/events/events.dart (hunk 2 above)
Comment (utkarshshendge) [reply lib/views/pages/events/events.dart:164]: > Does the type of exception matter here? If it's internet connectivity i.e. ClientException as you mentioned earlier then we should let them know that's the issue. Otherwise we show some other message if there is something they can do to resolve it. If nothing else, then generic error - maybe ask them to recreate it.

Oh yes, there's actually no need to show: `Could not delete event! Please try again later`
instead, we can show whether it's a client exception or server error.
Creating a commit for the same.
Thanks for pointing it out @dellyjm :)

**Comment by utkarshshendge** [comment]
> I approved the changes but please review my comments, I would like to have a response to them.

@dellyjm I have responded to the comments.
Thank you!

**Comment by dellyjm** [comment]
> 
> 
> > I approved the changes but please review my comments, I would like to have a response to them.
> 
> @dellyjm I have responded to the comments.
> Thank you!

thank you!
