### PR TITLE
Solves Exception toast overflow on register form screen

### LINKED ISSUE #227: Exception toast in register form screen has overflow errors.
### Problem
The exception toast in the register form has overflow errors. 

WhatsApp Image 2021-03-14 at 2 36 48 PM

### Possible solution
Wrapping the Text widget with an Expanded widget would solve the problem.

### PR DESCRIPTION
**Pull request by SriramPatibanda**
**What kind of change does this PR introduce?**

BugFix

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

No

**Summary**

The toast displayed on the register form screen when exceptions occur has renderflex overflow errors. This pull request solves that issue by wrapping the text widget with an expanded widget. This PR resolves #227 

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by Sagar2366** [comment]
@SriramPatibanda, please share the steps to reproduce this issue. Are you on master branch ? Recently major fix has been added and such issues are already fixed. Please let us know if you still seeing this issue.

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda, please share the steps to reproduce this issue. Are you on master branch ? Recently major fix has been added and such issues are already fixed. Please let us know if you still seeing this issue.

Hey I pulled the recent changes again and you're right, the issue is already fixed!!
Sorry for the PR. Will make sure this doesn't happen again.

**Comment by SriramPatibanda** [comment]
@Sagar2366 If you're the maintainer, can you please assign the issues to the people who are working on them already please? It's confusing whether I can start working on the issue or not.

**Comment by SriramPatibanda** [comment]
Closing the pull request as it has already been solved.

**Comment by SriramPatibanda** [comment]
@Sagar2366  I thought the issue was resolved but found out that this issue persists even now.

Steps to Reproduce the Issue:
1. Set a wrong URL on the home page.
2. Click Create an Account.
3. Fill in the form and click sign up.

**Comment by Sagar2366** [comment]
Not able to reproduce at my end. 
1. Pulled latest code from master branch
2. Provided wrong Organization URL
3. Create account, provide all required details
4. Click on sign up and no error thrown.

**Comment by SriramPatibanda** [comment]
> Not able to reproduce at my end.
> 
> 1. Pulled latest code from master branch
> 2. Provided wrong Organization URL
> 3. Create account, provide all required details
> 4. Click on sign up and no error thrown.

Oh, I see. It's occurring to me at random moments. Not the exact error but whenever the text is long, it overflows.
WhatsApp Image 2021-03-15 at 1 07 00 PM

If you see the above image, the error is different from the one that I got in #227 but nevertheless, it overflows.
Hence, I suggest using an expanded widget over the text widget.

**Comment by SriramPatibanda** [comment]
If it's too minor, the issue can be ignored and the PR can be closed.

**Comment by Sagar2366** [comment]
@SriramPatibanda, provided long text amd still not able to reproduce the issue. 
Provide more details on how to reproduce the issue - video would be preferable.

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda, provided long text amd still not able to reproduce the issue.
> Provide more details on how to reproduce the issue - video would be preferable.

@Sagar2366 
https://user-images.githubusercontent.com/56649197/111149034-5d3ec600-85b2-11eb-8024-919cb1786d4d.mp4

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda, provided long text amd still not able to reproduce the issue.
> Provide more details on how to reproduce the issue - video would be preferable.

@Sagar2366 here is the video of that issue. 
https://user-images.githubusercontent.com/56649197/111149161-865f5680-85b2-11eb-8ac5-6fe0410eba57.mp4

**Comment by Sagar2366** [comment]
Can you please show meaningful message in case of failure case ? which should be easily understandable by non-tech people.

**Comment by SriramPatibanda** [comment]
> Can you please show meaningful message in case of failure case ? which should be easily understandable by non-tech people.

Sure @Sagar2366 . I'm displaying "Sign Up unsuccessful. Please try again.". It is cool?

**Comment by SriramPatibanda** [comment]
@Sagar2366 The following changes have been made:
 - The Error message is changed to "Sign Up unsuccessful. Please try again"
 - The Text has been aligned to center
 - the color of the text has been changed from black to white to make the register form color pattern uniform.

File: lib/views/pages/login_signup/register_form.dart [hunk 1]
```diff
@@ -70,7 +70,7 @@ class RegisterFormState extends State<RegisterForm> {
       setState(() {
         _progressBarState = false;
       });
-      _exceptionToast(result.exception.toString().substring(16));
+      _exceptionToast('Sign Up unsuccessful. Please try again');
```
Comment (Sagar2366) [inline lib/views/pages/login_signup/register_form.dart:73]: Please change the message to "Invalid organization URL". It will give user clear idea what is going wrong.

Comment (SriramPatibanda) [reply lib/views/pages/login_signup/register_form.dart:73]: Sure! thing!

**Comment by SriramPatibanda** [comment]
The requested changes have been made. Kindly re-review the PR @Sagar2366 .

**Review by Sagar2366 — APPROVED** [review]
